services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
